name: "Verify that tag and workspace's versions match"

description: |
  Verifies that the tag's version matches the workspace's version.

  Will fail if the caller wasn't triggered by the push of a semver-formatted tag.

runs:
  using: "composite"
  steps:
    - name: Extract the version from the ref name
      id: extract-version-from-ref
      shell: bash
      run: |
        if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Workflow not triggered by a semver tag, ref is '$GITHUB_REF_NAME'"
          exit 1
        fi

        tag_version=${GITHUB_REF_NAME#v}
        echo "tag_version=$tag_version" >> $GITHUB_OUTPUT

    - name: Install yq (also installs tomlq)
      uses: mikefarah/yq@master

    - name: Verify that the tag's version matches the workspace's version
      shell: bash
      run: |
        tag_version=${{ steps.extract-version-from-ref.outputs.tag_version }}
        workspace_version=$(tomlq ".workspace.package.version" ./Cargo.toml)

        if [ "$tag_version" != "$workspace_version" ]; then
          echo "❌ Version mismatch!"
          echo "Tag version: $tag_version"
          echo "Workspace version: $workspace_version"
          exit 1
        fi
