name: "Add the private repos' deploy keys"

inputs:
  secrets:
    required: true

runs:
  using: "composite"
  steps:
    - name: Add the deploy keys of all private repos we depend on
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: |
          inputs.secrets.ABS_PATH_DEPLOY_KEY
          inputs.secrets.CAUCHY_DEPLOY_KEY
