name: "Add the private repos' deploy keys"

runs:
  using: "composite"
  steps:
    - name: Add the deploy keys of all private repos we depend on
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: |
          ${{ secrets.ABS_PATH_DEPLOY_KEY }}
          ${{ secrets.CAUCHY_DEPLOY_KEY }}
