name: "Nix, Cachix & devshell"

description: "Installs Nix, sets up Cachix and optionally enters a Nix devshell"

inputs:
  cachix-auth-token:
    description: "Auth token for pushing Nix artifacts to Cachix"
    required: true
  devshell:
    description: "Nix devshell to enter"
    required: false
    default: ""
  ssh-private-keys:
    description: "SSH deploy keys for private repositories"
    required: true

runs:
  using: "composite"
  steps:
    - name: Add deploy keys for private repos
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh-private-keys }}

    - name: Start timer for installing Nix
      id: nix-timer-start
      shell: bash
      run: echo "nix_start_time=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ github.token }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: "nomad"
        authToken: ${{ inputs.cachix-auth-token }}

    - name: End timer for installing Nix
      shell: bash
      run: |
        nix_end_time=$(date +%s)
        nix_duration=$((nix_end_time - ${{ steps.nix-timer-start.outputs.nix_start_time }}))
        echo "⏱️ Installing Nix and setting up Cachix took ${nix_duration}s"

    - name: Start timer for entering Nix devshell '${{ inputs.devshell }}'
      if: ${{ inputs.devshell != '' }}
      id: devshell-timer-start
      shell: bash
      run: echo "devshell_start_time=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Enter Nix devshell '${{ inputs.devshell }}'
      if: ${{ inputs.devshell != '' }}
      shell: bash
      run: nix run .#nix-develop-gha --accept-flake-config -- ${{ inputs.devshell }} --accept-flake-config

    - name: End timer for entering Nix devshell '${{ inputs.devshell }}'
      if: ${{ inputs.devshell != '' }}
      shell: bash
      run: |
        devshell_end_time=$(date +%s)
        devshell_duration=$((devshell_end_time - ${{ steps.devshell-timer-start.outputs.devshell_start_time }}))
        echo "⏱️ Entering Nix devshell '${{ inputs.devshell }}' took ${devshell_duration}s"
