//! TODO: docs.

extern crate alloc;

mod action;
mod actor_id;
mod api;
mod autocmd;
pub mod autocmds;
mod boo;
mod buffer;
mod byte_offset;
mod command;
mod command_args;
pub mod config;
mod context;
pub mod diagnostics;
mod editor;
mod event;
mod executor;
mod function;
mod join_handle;
mod log;
mod maybe_result;
mod module;
mod module_api;
mod module_commands;
mod module_name;
pub mod neovim;
mod nomad;
mod nomad_command;
mod point;
mod serde;
mod shared;
mod spawner;
mod subscription;
mod text;

pub use action::Action;
pub use actor_id::ActorId;
pub use autocmd::{Autocmd, AutocmdId, ShouldDetach};
pub use boo::Boo;
pub use buffer::Buffer;
pub use byte_offset::ByteOffset;
pub use command::Command;
pub use command_args::CommandArgs;
pub use context::Context;
pub use editor::Editor;
pub use event::Event;
pub use function::Function;
pub use module::Module;
pub use module_api::ModuleApi;
pub use module_name::ModuleName;
pub use nomad::Nomad;
pub use nomad_macros::module_name;
pub use shared::Shared;
pub use spawner::{JoinHandle, Spawner};
pub use subscription::{Emitter, Subscription};
pub use text::Text;
