//! TODO: docs.

extern crate alloc;

mod action;
mod action_name;
mod actor_id;
mod actor_map;
mod autocmd;
pub mod autocmds;
mod boo;
mod buf_attach;
mod buffer_id;
mod byte_offset;
mod command;
mod command_args;
pub mod config;
pub mod ctx;
pub mod diagnostics;
mod event;
pub mod events;
mod executor;
mod function;
mod join_handle;
mod log;
mod maybe_result;
mod module;
mod module_api;
mod module_commands;
mod module_name;
mod nomad;
mod nomad_command;
mod point;
mod replacement;
mod serde;
mod shared;
mod spawner;
mod text;

pub use action::{Action, FnAction};
pub use action_name::ActionName;
pub use actor_id::ActorId;
pub use autocmd::{AutoCommand, ShouldDetach};
pub use boo::Boo;
pub use buf_attach::BufAttachArgs;
pub use buffer_id::BufferId;
pub use byte_offset::ByteOffset;
pub use command::Command;
pub use command_args::CommandArgs;
pub use event::Event;
pub use function::Function;
pub use module::Module;
pub use module_api::ModuleApi;
pub use module_name::ModuleName;
pub use nomad::Nomad;
pub use nomad_macros::module_name;
pub use replacement::Replacement;
pub use shared::Shared;
pub use spawner::{JoinHandle, Spawner};
pub use text::Text;
